version: '3.8'

services:
  postgres:
    image: postgres
    container_name: url-shortener-postgres
    restart: always
    environment:
      POSTGRES_USER: ashok
      POSTGRES_PASSWORD: ashok123
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - urlnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ashok@example.com
      PGADMIN_DEFAULT_PASSWORD: ashok123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - urlnet

volumes:
  pgdata:

networks:
  urlnet:
    driver: bridge
